on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@1.4.4
        with:
          node-version: 12

      - run: npm i
      - run: npx eslint